-- AlterTable
ALTER TABLE "Gym" ADD COLUMN     "priceDay" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "priceMonth" DOUBLE PRECISION NOT NULL DEFAULT 500,
ADD COLUMN     "pricePromo" DOUBLE PRECISION NOT NULL DEFAULT 300,
ADD COLUMN     "priceYear" DOUBLE PRECISION NOT NULL DEFAULT 5000;
